Algoritmo "ex 12"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama 
// Descrição   : Conversaso de temperatura °F  -> °C
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/10/2023
Var
// Seção de Declarações das variáveis 
 fahrenheit:real
 C:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a temperatura em  °F para ser convertida em °C ")
leia(fahrenheit)

C <- ((fahrenheit - 32) * 5) / 9

escreval(C , "°C")


Fimalgoritmo